### ISSUE TITLE
A tool for one-time SSH servers

### ISSUE THREAD

**Issue by grncdr** [grncdr/otssh#1]
`otssh` is an SSH server for providing audited, single-use shell sessions from environments where a persistent daemon is undesirable.

## Usage

```
usage: otssh [-port=2022] [-log=<filename>] [-announce=<cmd>] -authorized-keys=<filename>

Starts an SSH server with a new host key that will run for exactly one session.
```

See the README for detailed documentation/requirements.

**Comment by neiser** [comment]
Hi @grncdr 

I really like that idea of building such a tool. I just wanted to leave feedback that I'm also quite impressed that you offer money that such a tool comes into existence. I'm really tempted to at least give it a try!

My approach would be to take the chance and learn more about Rust (I've some C++ experience but been entrenched in Java now for the last 3 years). 

Just by searching naively, I think the following rust crates could be useful:
* TLS: https://github.com/ctz/rustls or https://pijul.org/thrussh/
* CLI: https://github.com/clap-rs/clap and https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46

Rust also has the ability to create nice statically linked binaries since recently: https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1480-2020-11-19

I didn't find in 5 minutes how to spawn a `$SHELL` and send commands to/from it via SSH protocol, but I'm sure that's feasible. Anyway, I can't promise much, just wanted to leave my thoughts & links here. I hope that's fine.

**Comment by gerbyzation** [comment]
If @neiser isn't going to take this on I'd be interested to try and tackle this. Been looking for a project to excercise some golang on and think this would be quite suitable.

**Comment by neiser** [comment]
@gerbyzation Go ahead! (pun intended)

No seriously, I consider the chance that I'll come up with a decent solution worthy of the bounty to be low. So I don't want to block anyone else from trying with more free time and motivation than me.

**Comment by DomWilliams0** [comment]
I'd also be interested to take a shot, using Rust as I have a lot of experience with it. Happy to let @gerbyzation go (heh) for it first.

**Comment by michaelr524** [comment]
Hi 🙋‍♂️ 
I’ll do it in Rust as well, if none of the guys that announced their interest before me will do it.
I can do it in one week.

**Comment by navneethg** [comment]
Hello world. Didn't know we were expressing interest here, opened a separate issue as mentioned in the README. I'd love to take a shot at this with Go. If you care about the performance *deeply* (that is you prefer to Rust than Go) please let me know I'll drop off. Otherwise a very experienced engineer here, who is totally motivated to do it. ETA ~ 2 - 4 weeks including solid test cases, packaging and github workflows for CI/CD.

**Comment by grncdr** [comment]
Hey everybody :wave:

I was not expecting quite so many interested people all at once, which has put me in a position of needing to define the protocol for resolving conflicts. So here it is:

- I'll start with the first person to respond and work my way down. Explicitly naming the current candidate.
- A candidate will have ~24 hours to confirm they want to "lock" the bounty.
- If there's no response, or the current candidate has explicitly passed, I'll announce here that the _next_ person is now able to "lock" the bounty.
- This repeats until somebody actually commits.
- After committing that person has 1 week to produce _something_. This doesn't need to be a completed solution, but if there's no visible activity or progress after a week, I will move on to the next person. Life happens and we get busy (I know 😅 ).
- After the implementation works and has the features describe in the README, I'll pay the bounty, and everybody will have a nice new tool to use. 😄 

---

So: @neiser is up. You have until tomorrow to decide if you want to give it a shot, or pass it on to @gerbyzation .

**Comment by neiser** [comment]
@grncdr Alright, I'll spend the next two hours to see if I have any chance (then my wife calls for dinner, and you'll know what that means :joy:) . If I don't get anything running, I'll pass on. Stay tuned.

**Comment by neiser** [comment]
Ok, I think I can do it within a week. So I'd like to take the challenge. See progress in https://github.com/neiser/otssh I'll make a PR once I've arrived at a first version. It's dinner time now though :)

**Comment by grncdr** [comment]
Great! Have fun 😄

**Comment by geigerzaehler** [comment]
Hi there. I’m also interested in giving this a try in rust.

**Comment by neiser** [comment]
I spend some time on it today, but I think I'm lacking too much basic knowledge about rust and async/await in particular (current version is pushed at https://github.com/neiser/otssh, please, rust experts, have mercy with me :smiley_cat:). I think it's probably not that hard for someone how has more experience in tokio.

Passing the chance officially on to you, @gerbyzation

**Comment by navneethg** [comment]
@gerbyzation @DomWilliams0 if and only if you are ok with giving me a chance at a second shot at this, let me know. I'll take a day's silence as a no as well.

**Comment by grncdr** [comment]
No stress @neiser (fwiw I also haven't really learned how to use async/await in Rust 😅)

---

So now @gerbyzation has until tomorrow afternoon (more or less 15:30 Berlin time) to confirm he still wants to do it.

**Comment by gerbyzation** [comment]
thanks for the opportunity @neiser.

@grncdr I'm keen to take this on. Had a play with the golang.com/x/crypto/ssh and github.com/creack/pty and got something simple working.

@navneethg I'll shoot you an email as you're the only one who mentioned golang in here - let's talk and maybe we can work out a way to collaborate.

**Comment by gerbyzation** [comment]
Quick update: this is a quick spike I pulled together based of the example and a few other things: https://gist.github.com/gerbyzation/4c769c0fe5d5733d4a8421d18b493539. Have started working on a proper implementation backed by tests.

**Comment by grncdr** [comment]
Hey @gerbyzation, are you still making progress?

**Comment by gerbyzation** [comment]
@grncdr yup, last week was a bit busy due to a deadline but made some progress on the weekend and will have more free time during this week to work on it. Spent a little time on working out how to execute and test a binary, so I can properly test drive it from the outside now.

Will get something up on github this week so there's a bit more visibility in my progress.

Had two questions for you regarding generating the host key and announcing it:
 *  keeping the new host key in memory should be fine right, as there would be a new key for each session?
 *  can you give me an example on how you'd use the `-anounce` argument? I think I understand what it should do but would be good to have an example of how it could/would be used.

**Comment by grncdr** [comment]
Awesome 😄 

> keeping the new host key in memory should be fine right, as there would be a new key for each session?

Yep exactly this.

> can you give me an example on how you'd use the -anounce argument?

Sure, this is a bit contrived, but something like this is what I had in mind:

```
otssh [other args] -announce send_me_a_slack_dm
```

The point is that the `send_me_a_slack_dm` command is pluggable. It could also be something like `upload_to_s3` or any other way a user wants to get the host keys back to themselves. (For reference, I am currently tailing the output of my Ruby wrapper script via my cloud-hosting provider and parsing the `tinyssh` output, anything would be better than that :wink:)

**Comment by grncdr** [comment]
Any updates @gerbyzation or should I move on to the next person in the list?

**Comment by gerbyzation** [comment]
@grncdr yes, I've been pushing my work to https://github.com/gerbyzation/otssh/tree/dev. At the moment the `-authorized-keys` and `-port` flags are working and you can connect to an interactive session. I worked on the test setup a bit too - adding support to run assertions on `stdout`/`stderr` while the process is still running. I should be able to focus more on delivering functionality now. Aiming to have the `-log`, `-anounce` and `-timeout` flag working by start of next week. Will send a new update after the weekend.

**Comment by grncdr** [comment]
ah sorry, I didn't see there was a `dev` branch. I'll check it out :)

**Comment by gerbyzation** [comment]
@grncdr I've added implementations for the `-log`, `-announce` and `-timeout` flag. Had a few more questions that I was hoping to get your thoughts on:

Logging:
 * when `--log` is provided, should output be written to both the file as well as stdout or only the logfile?
 * I'm thinking it could improve readability of the logs if the transcript of the shell session gets some kind of line prefix. Have any ideas/opinions on this?

Anounce:
 * I assumed the output from the announce command should be displayed/logged?
 * Should the program fail when the announce commands exits with a non-zero status code or continue despite failure?

**Comment by grncdr** [comment]
For `--log` I think it's fine as you've done it, writing only to the log file *or* stdout. I personally don't have any use case for a line prefix, as anywhere I'm consuming/aggregating logs is already adding timestamps etc.

For `--announce`, yes please log any output. The program should fail with an ["Announce failed"](https://github.com/grncdr/otssh#announce-failed-exit_code-stderr) error if the announce command exits with a non-zero status. This gives the announce command the flexibility to handle retries/fallbacks etc.

**Comment by grncdr** [comment]
I just gave the current version a little test-drive. Super nice so far! One issue I noticed is that lines & columns seem to be getting swapped in the terminal dimensions, leading to some funny issues when opening e.g. an editor.

Can you send an email to me@(my full name).com and let me know how you want to be paid? PayPal or bank transfer (SEPA) is fine for me.
